const mapNames = {
    'Baltic_Main': 'Erangel (Remastered)',
    'Chimera_Main': 'Paramo',
    'Desert_Main': 'Miramar',
    'DihorOtok_Main': 'Vikendi',
    'Erangel_Main': 'Erangel',
    'Heaven_Main': 'Haven',
    'Kiki_Main': 'Deston',
    'Range_Main': 'Camp Jackal',
    'Savage_Main': 'Sanhok',
    'Summerland_Main': 'Karakin',
    'Tiger_Main': 'Taego',
};

const locationNames = {
    ArmShot: 'Bras',
    HeadShot: 'Tête',
    LegShot: 'Jambe',
    None: 'Aucun',
    NonSpecific: 'Générique',
    PelvisShot: 'Burnes',
    TorsoShot: 'Torse',
};

const causerNames = {
    'AIPawn_Base_Female_C': 'AI Player',
    'AIPawn_Base_Male_C': 'AI Player',
    'AirBoat_V2_C': 'Airboat',
    'AquaRail_A_01_C': 'Aquarail',
    'AquaRail_A_02_C': 'Aquarail',
    'AquaRail_A_03_C': 'Aquarail',
    'BP_ATV_C': 'Quad',
    'BP_BRDM_C': 'BRDM-2',
    'BP_Bicycle_C': 'Mountain Bike',
    'BP_CoupeRB_C': 'Coupe RB',
    'BP_DO_Circle_Train_Merged_C': 'Train',
    'BP_DO_Line_Train_Dino_Merged_C': 'Train',
    'BP_DO_Line_Train_Merged_C': 'Train',
    'BP_Dirtbike_C': 'Dirt Bike',
    'BP_DronePackage_Projectile_C': 'Drone',
    'BP_Eragel_CargoShip01_C': 'Ferry Damage',
    'BP_FakeLootProj_AmmoBox_C': 'Loot Truck',
    'BP_FakeLootProj_MilitaryCrate_C': 'Loot Truck',
    'BP_FireEffectController_C': 'Molotov Fire',
    'BP_FireEffectController_JerryCan_C': 'Jerrycan Fire',
    'BP_Helicopter_C': 'Pillar Scout Helicopter',
    'BP_IncendiaryDebuff_C': 'Burn',
    'BP_JerryCanFireDebuff_C': 'Burn',
    'BP_JerryCan_FuelPuddle_C': 'Burn',
    'BP_KillTruck_C': 'Kill Truck',
    'BP_LootTruck_C': 'Loot Truck',
    'BP_M_Rony_A_01_C': 'Rony',
    'BP_M_Rony_A_02_C': 'Rony',
    'BP_M_Rony_A_03_C': 'Rony',
    'BP_Mirado_A_02_C': 'Mirado',
    'BP_Mirado_A_03_Esports_C': 'Mirado',
    'BP_Mirado_Open_03_C': 'Mirado (open top)',
    'BP_Mirado_Open_04_C': 'Mirado (open top)',
    'BP_Mirado_Open_05_C': 'Mirado (open top)',
    'BP_MolotovFireDebuff_C': 'Molotov Fire Damage',
    'BP_Motorbike_04_C': 'Motorcycle',
    'BP_Motorbike_04_Desert_C': 'Motorcycle',
    'BP_Motorbike_04_SideCar_C': 'Motorcycle (w/ Sidecar)',
    'BP_Motorbike_04_SideCar_Desert_C': 'Motorcycle (w/ Sidecar)',
    'BP_Motorbike_Solitario_C': 'Motorcycle',
    'BP_Motorglider_C': 'Motor Glider',
    'BP_Motorglider_Green_C': 'Motor Glider',
    'BP_Niva_01_C': 'Zima',
    'BP_Niva_02_C': 'Zima',
    'BP_Niva_03_C': 'Zima',
    'BP_Niva_04_C': 'Zima',
    'BP_Niva_05_C': 'Zima',
    'BP_Niva_06_C': 'Zima',
    'BP_Niva_07_C': 'Zima',
    'BP_PickupTruck_A_01_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_A_02_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_A_03_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_A_04_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_A_05_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_A_esports_C': 'Pickup Truck (closed top)',
    'BP_PickupTruck_B_01_C': 'Pickup Truck (open top)',
    'BP_PickupTruck_B_02_C': 'Pickup Truck (open top)',
    'BP_PickupTruck_B_03_C': 'Pickup Truck (open top)',
    'BP_PickupTruck_B_04_C': 'Pickup Truck (open top)',
    'BP_PickupTruck_B_05_C': 'Pickup Truck (open top)',
    'BP_Pillar_Car_C': 'Pillar Security Car',
    'BP_PonyCoupe_C': 'Pony Coupe',
    'BP_Porter_C': 'Porter',
    'BP_Scooter_01_A_C': 'Scooter',
    'BP_Scooter_02_A_C': 'Scooter',
    'BP_Scooter_03_A_C': 'Scooter',
    'BP_Scooter_04_A_C': 'Scooter',
    'BP_Snowbike_01_C': 'Snowbike',
    'BP_Snowbike_02_C': 'Snowbike',
    'BP_Snowmobile_01_C': 'Snowmobile',
    'BP_Snowmobile_02_C': 'Snowmobile',
    'BP_Snowmobile_03_C': 'Snowmobile',
    'BP_Spiketrap_C': 'Spike Trap',
    'BP_TslGasPump_C': 'Gas Pump',
    'BP_TukTukTuk_A_01_C': 'Tukshai',
    'BP_TukTukTuk_A_02_C': 'Tukshai',
    'BP_TukTukTuk_A_03_C': 'Tukshai',
    'BP_Van_A_01_C': 'Van',
    'BP_Van_A_02_C': 'Van',
    'BP_Van_A_03_C': 'Van',
    'BattleRoyaleModeController_Chimera_C': 'Bluezone',
    'BattleRoyaleModeController_Def_C': 'Bluezone',
    'BattleRoyaleModeController_Desert_C': 'Bluezone',
    'BattleRoyaleModeController_DihorOtok_C': 'Bluezone',
    'BattleRoyaleModeController_Heaven_C': 'Bluezone',
    'BattleRoyaleModeController_Kiki_C': 'Bluezone',
    'BattleRoyaleModeController_Savage_C': 'Bluezone',
    'BattleRoyaleModeController_Summerland_C': 'Bluezone',
    'BattleRoyaleModeController_Tiger_C': 'Bluezone',
    'BlackZoneController_Def_C': 'Blackzone',
    'Bluezonebomb_EffectActor_C': 'Bluezone Grenade',
    'Boat_PG117_C': 'PG-117',
    'Buff_DecreaseBreathInApnea_C': 'Drowning',
    'Buggy_A_01_C': 'Buggy',
    'Buggy_A_02_C': 'Buggy',
    'Buggy_A_03_C': 'Buggy',
    'Buggy_A_04_C': 'Buggy',
    'Buggy_A_05_C': 'Buggy',
    'Buggy_A_06_C': 'Buggy',
    'Carepackage_Container_C': 'Care Package',
    'Dacia_A_01_v2_C': 'Dacia',
    'Dacia_A_01_v2_snow_C': 'Dacia',
    'Dacia_A_02_v2_C': 'Dacia',
    'Dacia_A_03_v2_C': 'Dacia',
    'Dacia_A_03_v2_Esports_C': 'Dacia',
    'Dacia_A_04_v2_C': 'Dacia',
    'DroppedItemGroup': 'Object Fragments',
    'EmergencyAircraft_Tiger_C': 'Emergency Aircraft',
    'Jerrycan': 'Jerrycan',
    'JerrycanFire': 'Jerrycan Fire',
    'Lava': 'Lava',
    'Mortar_Projectile_C': 'Mortar Projectile',
    'None': 'None',
    'PG117_A_01_C': 'PG-117',
    'PanzerFaust100M_Projectile_C': 'Panzerfaust Projectile',
    'PlayerFemale_A_C': 'Player',
    'PlayerMale_A_C': 'Player',
    'ProjC4_C': 'C4',
    'ProjGrenade_C': 'Frag Grenade',
    'ProjIncendiary_C': 'Incendiary Projectile',
    'ProjMolotov_C': 'Molotov Cocktail',
    'ProjMolotov_DamageField_Direct_C': 'Molotov Cocktail Fire Field',
    'ProjStickyGrenade_C': 'Sticky Bomb',
    'RacingDestructiblePropaneTankActor_C': 'Propane Tank',
    'RacingModeContorller_Desert_C': 'Bluezone',
    'RedZoneBomb_C': 'Redzone',
    'RedZoneBombingField': 'Redzone',
    'RedZoneBombingField_Def_C': 'Redzone',
    'TslDestructibleSurfaceManager': 'Destructible Surface',
    'TslPainCausingVolume': 'Lava',
    'Uaz_A_01_C': 'UAZ (open top)',
    'Uaz_Armored_C': 'UAZ (armored)',
    'Uaz_B_01_C': 'UAZ (soft top)',
    'Uaz_B_01_esports_C': 'UAZ (soft top)',
    'Uaz_C_01_C': 'UAZ (hard top)',
    'UltAIPawn_Base_Female_C': 'Player',
    'UltAIPawn_Base_Male_C': 'Player',
    'WeapACE32_C': 'ACE32',
    'WeapAK47_C': 'AKM',
    'WeapAUG_C': 'AUG A3',
    'WeapAWM_C': 'AWM',
    'WeapBerreta686_C': 'S686',
    'WeapBerylM762_C': 'Beryl',
    'WeapBizonPP19_C': 'Bizon',
    'WeapCowbarProjectile_C': 'Crowbar Projectile',
    'WeapCowbar_C': 'Crowbar',
    'WeapCrossbow_1_C': 'Crossbow',
    'WeapDP12_C': 'DBS',
    'WeapDP28_C': 'DP-28',
    'WeapDesertEagle_C': 'Deagle',
    'WeapDuncansHK416_C': 'M416',
    'WeapFNFal_C': 'SLR',
    'WeapG18_C': 'P18C',
    'WeapG36C_C': 'G36C',
    'WeapGroza_C': 'Groza',
    'WeapHK416_C': 'M416',
    'WeapJuliesKar98k_C': 'Kar98k',
    'WeapK2_C': 'K2',
    'WeapKar98k_C': 'Kar98k',
    'WeapL6_C': 'Lynx AMR',
    'WeapLunchmeatsAK47_C': 'AKM',
    'WeapM16A4_C': 'M16A4',
    'WeapM1911_C': 'P1911',
    'WeapM249_C': 'M249',
    'WeapM24_C': 'M24',
    'WeapM9_C': 'P92',
    'WeapMG3_C': 'MG3',
    'WeapMP5K_C': 'MP5K',
    'WeapMP9_C': 'MP9',
    'WeapMacheteProjectile_C': 'Machete Projectile',
    'WeapMachete_C': 'Machete',
    'WeapMadsQBU88_C': 'QBU88',
    'WeapMini14_C': 'Mini 14',
    'WeapMk12_C': 'Mk12',
    'WeapMk14_C': 'Mk14 EBR',
    'WeapMk47Mutant_C': 'Mk47 Mutant',
    'WeapMosinNagant_C': 'Mosin-Nagant',
    'WeapNagantM1895_C': 'R1895',
    'WeapOriginS12_C': 'O12',
    'WeapP90_C': 'P90',
    'WeapPanProjectile_C': 'Pan Projectile',
    'WeapPan_C': 'Pan',
    'WeapPanzerFaust100M1_C': 'Panzerfaust',
    'WeapQBU88_C': 'QBU88',
    'WeapQBZ95_C': 'QBZ95',
    'WeapRhino_C': 'R45',
    'WeapSCAR-L_C': 'SCAR-L',
    'WeapSKS_C': 'SKS',
    'WeapSaiga12_C': 'S12K',
    'WeapSawnoff_C': 'Sawed-off',
    'WeapSickleProjectile_C': 'Sickle Projectile',
    'WeapSickle_C': 'Sickle',
    'WeapThompson_C': 'Tommy Gun',
    'WeapTurret_KillTruck_Main_C': 'Kill Truck Turret',
    'WeapUMP_C': 'UMP9',
    'WeapUZI_C': 'Micro Uzi',
    'WeapVSS_C': 'VSS',
    'WeapVector_C': 'Vector',
    'WeapWin94_C': 'Win94',
    'WeapWinchester_C': 'S1897',
    'Weapvz61Skorpion_C': 'Skorpion',
};

const gameModes = {
    duo: { gameType: null, gameMode: 'Duo', gamePOV: 'TPP' },
    'duo-fpp': { gameType: null, gameMode: 'Duo', gamePOV: 'FPP' },
    solo: { gameType: null, gameMode: 'Solo', gamePOV: 'TPP' },
    'solo-fpp': { gameType: null, gameMode: 'Solo', gamePOV: 'FPP' },
    squad: { gameType: null, gameMode: 'Squad', gamePOV: 'TPP' },
    'squad-fpp': { gameType: null, gameMode: 'Squad', gamePOV: 'FPP' },
    'conquest-duo': { gameType: 'Conquest', gameMode: 'Duo', gamePOV: 'TPP' },
    'conquest-duo-fpp': { gameType: 'Conquest', gameMode: 'Duo', gamePOV: 'FPP' },
    'conquest-solo': { gameType: 'Conquest', gameMode: 'Solo', gamePOV: 'TPP' },
    'conquest-solo-fpp': { gameType: 'Conquest', gameMode: 'Solo', gamePOV: 'FPP' },
    'conquest-squad': { gameType: 'Conquest', gameMode: 'Squad', gamePOV: 'TPP' },
    'conquest-squad-fpp': { gameType: 'Conquest', gameMode: 'Squad', gamePOV: 'FPP' },
    'esports-duo': { gameType: 'Esports', gameMode: 'Duo', gamePOV: 'TPP' },
    'esports-duo-fpp': { gameType: 'Esports', gameMode: 'Duo', gamePOV: 'FPP' },
    'esports-solo': { gameType: 'Esports', gameMode: 'Solo', gamePOV: 'TPP' },
    'esports-solo-fpp': { gameType: 'Esports', gameMode: 'Solo', gamePOV: 'FPP' },
    'esports-squad': { gameType: 'Esports', gameMode: 'Squad', gamePOV: 'TPP' },
    'esports-squad-fpp': { gameType: 'Esports', gameMode: 'Squad', gamePOV: 'FPP' },
    'normal-duo': { gameType: 'Normal', gameMode: 'Duo', gamePOV: 'TPP' },
    'normal-duo-fpp': { gameType: 'Normal', gameMode: 'Duo', gamePOV: 'FPP' },
    'normal-solo': { gameType: 'Normal', gameMode: 'Solo', gamePOV: 'TPP' },
    'normal-solo-fpp': { gameType: 'Normal', gameMode: 'Solo', gamePOV: 'FPP' },
    'normal-squad': { gameType: 'Normal', gameMode: 'Squad', gamePOV: 'TPP' },
    'normal-squad-fpp': { gameType: 'Normal', gameMode: 'Squad', gamePOV: 'FPP' },
    'war-duo': { gameType: 'War', gameMode: 'Duo', gamePOV: 'TPP' },
    'war-duo-fpp': { gameType: 'War', gameMode: 'Duo', gamePOV: 'FPP' },
    'war-solo': { gameType: 'War', gameMode: 'Solo', gamePOV: 'TPP' },
    'war-solo-fpp': { gameType: 'War', gameMode: 'Solo', gamePOV: 'FPP' },
    'war-squad': { gameType: 'War', gameMode: 'Squad', gamePOV: 'TPP' },
    'war-squad-fpp': { gameType: 'War', gameMode: 'Squad', gamePOV: 'FPP' },
    'zombie-duo': { gameType: 'Zombie', gameMode: 'Duo', gamePOV: 'TPP' },
    'zombie-duo-fpp': { gameType: 'Zombie', gameMode: 'Duo', gamePOV: 'FPP' },
    'zombie-solo': { gameType: 'Zombie', gameMode: 'Solo', gamePOV: 'TPP' },
    'zombie-solo-fpp': { gameType: 'Zombie', gameMode: 'Solo', gamePOV: 'FPP' },
    'zombie-squad': { gameType: 'Zombie', gameMode: 'Squad', gamePOV: 'TPP' },
    'zombie-squad-fpp': { gameType: 'Zombie', gameMode: 'Squad', gamePOV: 'FPP' },
    'lab-tpp': { gameType: 'Lab', gameMode: 'None', gamePOV: 'TPP' },
    'lab-fpp': { gameType: 'Lab', gameMode: 'None', gamePOV: 'FPP' },
    'tdm': { gameType: 'TDM', gameMode: 'None', gamePOV: 'FPP' },
};

const itemIdToDamageCauser = {
    Item_Weapon_AK47_C: 'WeapAK47_C',
    Item_Weapon_AUG_C: 'WeapAUG_C',
    Item_Weapon_AWM_C: 'WeapAWM_C',
    Item_Weapon_Berreta686_C: 'WeapBerreta686_C',
    Item_Weapon_BerylM762_C: 'WeapBerylM762_C',
    Item_Weapon_BizonPP19_C: 'WeapBizonPP19_C',
    Item_Weapon_Cowbar_C: 'WeapCowbar_C',
    Item_Weapon_Crossbow_C: 'WeapCrossbow_1_C',
    Item_Weapon_DesertEagle_C: 'WeapDesertEagle_C',
    Item_Weapon_DP12_C: 'WeapDP12_C',
    Item_Weapon_DP28_C: 'WeapDP28_C',
    Item_Weapon_FNFal_C: 'WeapFNFal_C',
    Item_Weapon_G18_C: 'WeapG18_C',
    Item_Weapon_G36C_C: 'WeapG36C_C',
    Item_Weapon_Grenade_C: 'ProjGrenade_C',
    Item_Weapon_Grenade_Warmode_C: 'ProjGrenade_C',
    Item_Weapon_Groza_C: 'WeapGroza_C',
    Item_Weapon_HK416_C: 'WeapHK416_C',
    Item_Weapon_Kar98k_C: 'WeapKar98k_C',
    Item_Weapon_M16A4_C: 'WeapM16A4_C',
    Item_Weapon_M1911_C: 'WeapM1911_C',
    Item_Weapon_M249_C: 'WeapM249_C',
    Item_Weapon_M24_C: 'WeapM24_C',
    Item_Weapon_M9_C: 'WeapM9_C',
    Item_Weapon_Machete_C: 'WeapMachete_C',
    Item_Weapon_Mini14_C: 'WeapMini14_C',
    Item_Weapon_Mk14_C: 'WeapMk14_C',
    Item_Weapon_Mk47Mutant_C: 'WeapMk47Mutant_C',
    Item_Weapon_Molotov_C: 'ProjMolotov_C',
    Item_Weapon_MP5K_C: 'WeapMP5K_C',
    Item_Weapon_NagantM1895_C: 'WeapNagantM1895_C',
    Item_Weapon_Pan_C: 'WeapPan_C',
    Item_Weapon_QBU88_C: 'WeapQBU88_C',
    Item_Weapon_QBZ95_C: 'WeapQBZ95_C',
    Item_Weapon_Rhino_C: 'WeapRhino_C',
    Item_Weapon_Saiga12_C: 'WeapSaiga12_C',
    Item_Weapon_Sawnoff_C: 'WeapSawnoff_C',
    'Item_Weapon_SCAR-L_C': 'WeapSCAR-L_C',
    Item_Weapon_Sickle_C: 'WeapSickle_C',
    Item_Weapon_SKS_C: 'WeapSKS_C',
    Item_Weapon_SpikeTrap_C: 'BP_Spiketrap_C',
    Item_Weapon_StickyGrenade_C: 'ProjStickyGrenade_C',
    Item_Weapon_Thompson_C: 'WeapThompson_C',
    Item_Weapon_UMP_C: 'WeapUMP_C',
    Item_Weapon_UZI_C: 'WeapUZI_C',
    Item_Weapon_Vector_C: 'WeapVector_C',
    Item_Weapon_VSS_C: 'WeapVSS_C',
    Item_Weapon_vz61Skorpion_C: 'Weapvz61Skorpion_C',
    Item_Weapon_Win1894_C: 'WeapWin94_C',
    Item_Weapon_Winchester_C: 'WeapWinchester_C',
};

exports.mapNames = mapNames;
exports.locationNames = locationNames;
exports.causerNames = causerNames;
exports.gameModes = gameModes;
exports.itemIdToDamageCauser = itemIdToDamageCauser;
